module Idura.FSharp.Analyzers.Tests.TestHelpers

open System.Collections.Concurrent
open System.Collections.Generic
open System.IO
open System.Text.Json
open System.Text.Json.Serialization
open System.Threading.Tasks

open Xunit
open Snapshooter
open Snapshooter.Xunit

open FSharp.Compiler.CodeAnalysis
open FSharp.Compiler.Text
open FSharp.Analyzers.SDK
open FSharp.Analyzers.SDK.Testing


// This is necessary because the Range type is self-referencing and thus unrenderable with the default setup
module RangeHack =
    type RangeRendition = {
        End: Position
        EndColumn: int
        EndLine: int
        FileName: string
        Start: Position
        StartColumn: int
        StartLine: int
    }

    type MessageRendition = {
        Code: string
        Fixes: Fix list
        Message: string
        Range : RangeRendition
        Severity: Severity
        Type: string
    }

    let private renderRange (range: Range) : RangeRendition = {
        End = range.End
        EndColumn = range.EndColumn
        EndLine = range.EndLine
        FileName = range.FileName
        Start = range.Start
        StartColumn = range.StartColumn
        StartLine = range.StartLine
    }

    let renderMessage (msg : Message) : MessageRendition = {
        Code = msg.Code
        Fixes = msg.Fixes
        Message = msg.Message
        Range = renderRange msg.Range
        Severity = msg.Severity
        Type = msg.Type
    }

type TestFiles =
    static member private dataFolder = Path.Combine [|__SOURCE_DIRECTORY__; "data" |]

    /// Gets the source code and file names of all test programs in the specified directory.
    static member GetSources (directory: string) : IEnumerable<string[]> =
        let dir = Path.Combine [|TestFiles.dataFolder; directory |]
        let getSource filename = filename |> File.ReadAllText
        let testName filename = Path.GetRelativePath(dir, filename)
        let data filename = [| getSource filename; testName filename |]

        let filenames = Directory.GetFiles dir
        Array.map data filenames

    /// Gets the source code of a test program in the specified file.
    static member GetSource (file: string) : string =
        Path.Combine [|TestFiles.dataFolder; file |]
        |> File.ReadAllText

// Building the options restores packages, drives MSBuild and parses the resulting binlog, which
// costs about as much as running a test case. They do not depend on the program being analysed, so
// each distinct combination is built once and every case awaits the same task.
//
// Sharing them is not just an optimisation. mkOptionsFromProject caches the binlog in a temp file
// named after the framework and the packages only, and does not guard it against concurrent access.
// Two test classes asking for the same combination at the same time race on that file, and the one
// that loses reads a half-written binlog. mkOptionsFromProject swallows the resulting exception and
// hands back FSharpProjectOptions.zero, so the failure surfaces much later as an unrelated-looking
// error from the compiler. Building each combination exactly once keeps the classes off each
// other's cache entry.
let private optionsCache = ConcurrentDictionary<string, Lazy<Task<FSharpProjectOptions>>>()

/// The project options for a temporary project targeting the given framework and referencing the
/// given packages. The test programs are analysed as if they were part of that project.
let projectOptions (framework: string) (packages: Package list) : Async<FSharpProjectOptions> = async {
    let key =
        packages
        |> List.map string
        |> List.sort
        |> List.append [ framework ]
        |> String.concat "_"

    let build = optionsCache.GetOrAdd(key, fun _ -> lazy mkOptionsFromProject framework packages)
    let! opts = Async.AwaitTask build.Value

    // mkOptionsFromProject reports a failed build by returning FSharpProjectOptions.zero rather than
    // throwing, which turns into confusing errors from the compiler once the tests start using the
    // options. Fail here instead, where the cause is still obvious.
    if Array.isEmpty opts.SourceFiles && Array.isEmpty opts.OtherOptions then
        failwith
            $"Could not build the project options for %s{key}. The temporary project that \
              mkOptionsFromProject builds to obtain them failed to build; its output is on stdout."

    return opts
}

let jsonOptions =  JsonFSharpOptions.Default().ToJsonSerializerOptions()

/// Serializes the messages generated by an analyzer and takes a snapshot of the serialization.
let private snapshotMessages (snapshotName: SnapshotFullName) (messages: Message list) =
    let renderedMessages = List.map RangeHack.renderMessage messages
    let rawMessage = JsonSerializer.Serialize(renderedMessages, jsonOptions)

    Snapshot.Match(rawMessage, snapshotName)

/// Tests that the given analyzer:
/// - Produces at least one message when run on the given program
/// - Produces the same messages as in the snapshot for the given program.
///
/// The snapshotName must be passed in by the caller due to limitations in Snapshooter.
let runPositiveTest snapshotName setupContext analyzer program = async {
    let! opts = setupContext()
    let ctx = getContext opts program
    let! msgs = analyzer ctx
    Assert.NotEmpty msgs
    snapshotMessages snapshotName msgs
}

/// The messages the given analyzer produces for the named program under 'data', for the tests that
/// assert on the messages themselves.
let messagesFor setupContext (analyzer : CliContext -> Async<Message list>) (file: string) = async {
    let! opts = setupContext()
    let program = TestFiles.GetSource file
    let ctx = getContext opts program
    return! analyzer ctx
}

/// Tests that the given analyzer produces no messages for the given program.
let runNegativeTest setupContext (analyzer : CliContext -> Async<Message list>) program = async {
    let! opts = setupContext()
    let ctx = getContext opts program
    let! msgs = analyzer ctx
    Assert.Empty msgs
}
